dev-1.x-download-trustpolicy-from-tar: Updated changes to policy agent in order to extract the encrypted image and the trust policy Removed the glance client command line utility as we don't need to download the trust policy from the glance anymore. It will be part of the tar ball downloaded by the nova.

diff --git a/linux/ubuntu/src/main/resources/policyagent b/linux/ubuntu/src/main/resources/policyagent
--- a/linux/ubuntu/src/main/resources/policyagent
+++ b/linux/ubuntu/src/main/resources/policyagent
@@ -2,18 +2,19 @@
 logfile=/var/log/policyagent.log
 configfile=/opt/policyagent/configuration/policyagent.env
 
-KMSPROXY_IPADDRESS=$(grep "KMS_PROXY_IP" $configfile | cut -d "=" -f2)
-INSTANCE_DIR="/var/lib/nova/instances/"
-
-verifierJavaLoc=/usr/local/bin/
-javaClassName=Validate
 export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
 export PATH=$PATH:/usr/lib/jvm/java-7-openjdk-amd64/jre/bin
 export CLASSPATH=/usr/lib/jvm/java-7-openjdk-amd64/lib/
 
-#source /opt/policyagent/configuration/admin-openrc.sh
+kms_proxy_ipaddress=$(grep "KMS_PROXY_IP" $configfile | cut -d "=" -f2)
+INSTANCE_DIR="/var/lib/nova/instances/"
+verifierJavaLoc=/usr/local/bin/
+javaClassName=Validate
 
-if [ ! -f $logfile ]; then touch $logfile; fi
+
+if [ ! -f $logfile ]; then 
+   touch $logfile; 
+fi
 
 # this command accepts two parameters:  filename, extension
 # the return value is the filename without the extension, or just the filename if it
@@ -83,7 +84,7 @@ openssl_encrypted_file() {
   local filename="$1"
   encheader=`hd -n 8 $filename | head -n 1 | grep "Salted__"`
   if [ -n "$encheader" ]; then
-    return 0
+      return 0
   fi
   return 1
 }
@@ -92,8 +93,8 @@ pa_encrypt() {
   local infile="$1"
   local encfile="$infile.enc"
   if [ ! -f $infile ]; then
-    echo "error: failed to encrypt $infile: file not found"
-    return 1
+     echo "error: failed to encrypt $infile: file not found"
+     return 1
   fi
   if openssl_encrypted_file $infile; then
     echo "error: failed to encrypt $infile: already encrypted";
@@ -102,8 +103,8 @@ pa_encrypt() {
   # XXX TODO need to change ciphers to aes-256-cbc and also add hmac for authentication!
   openssl enc -aes-128-ofb -in "$infile" -out "$encfile" -pass pass:password
   if openssl_encrypted_file $encfile; then
-    mv $encfile $infile
-    return 0
+     mv $encfile $infile
+     return 0
   fi
   echo "error: failed to encrypt $infile"
   return 3
@@ -116,49 +117,45 @@ pa_decrypt() {
    PRIVATE_KEY=/opt/trustagent/configuration/bindingkey.blob
   
   if [ ! -f $infile ]; then
-    echo "error: failed to decrypt $infile: file not found"
-    return 1
+     echo "error: failed to decrypt $infile: file not found"
+     return 1
   fi
   if ! openssl_encrypted_file $infile; then
-    echo "error: failed to decrypt $infile: not encrypted";
-    return 1
+     echo "error: failed to decrypt $infile: not encrypted";
+     return 1
   fi
   if [ -n "$IMAGE_ID" ]; then
-    pa_log "Found encrypted image: $IMAGE_ID"
+     pa_log "Found encrypted image: $IMAGE_ID"
   fi
 
   # XXX DEBUG for debugging only - copy the original image file to a tmp location for dev to look at it after
-  cp $infile /tmp/image.enc
+  #cp $infile /tmp/image.enc
 
-  # file is encrypted -- but we need the decryption key. pa_request_dek will
-  # request it from the key mgmt svc and place it in the var MH_DEK
-  # in order to request the dek we need to know the url from where to download
-  # it, which must be provided as an argument --dek-url
-  # ravindra: commenting the call pa_request_dek and putting hardcoded key 
   pa_request_dek $DEK_URL
+  
   # XXX TODO (see note in pa_encrypt) need to change ciphers to aes-256-cbc and also add hmac for authentication!
   #openssl enc -d -aes-128-ofb -in "$infile" -out "$decfile" -pass pass:password
  
- #Uncomment the following line with new KMS integration
-    #KEY_ID=$INSTANCE_DIR/$IMAGE_ID".key"
-    #tpm_unbindaeskey -k $PRIVATE_KEY -i $KEY_ID  -o $KEY_ID.dek
-    #openssl enc -d -aes-128-ofb -in "$infile" -out "$decfile" -pass env:$KEY_ID.dek
+  #Uncomment the following line with new KMS integration
+    #key_id=$INSTANCE_DIR/$IMAGE_ID".key"
+    #tpm_unbindaeskey -k $PRIVATE_KEY -i $key_id  -o $key_id.dek
+    #openssl enc -d -aes-128-ofb -in "$infile" -out "$decfile" -pass env:$key_id.dek
   #End of decrytion
 
   #delete these lines after uncommention above block
    export MH_DEK_DECODED=`openssl enc -base64 -d <<< $MH_DEK`
    pa_log "mh dek decoded::: $MH_DEK_DECODED";
    openssl enc -d -aes-128-ofb -in "$infile" -out "$decfile" -pass env:MH_DEK_DECODED
- #end of delete
+  #end of delete
 
   if ! openssl_encrypted_file $decfile; then
-    if [ -n "$IMAGE_ID" ]; then
-      pa_log "Decrypted image: $IMAGE_ID"
-      # XXX DEBUG for debugging only - 
-      cp $decfile /tmp/image.dec
-    fi
-    mv $decfile $infile
-    return 0
+     if [ -n "$IMAGE_ID" ]; then
+         pa_log "Decrypted image: $IMAGE_ID"
+         # XXX DEBUG for debugging only - 
+         #cp $decfile /tmp/image.dec
+     fi
+     mv $decfile $infile
+     return 0
   fi
   echo "error: failed to decrypt $infile"
   return 2
@@ -196,11 +193,10 @@ pa_launch() {
   pa_log "DEK URL: $DEK_URL"
   pa_log "MANIFEST UUID: $MANIFEST_UUID"
   pa_log "INSTANCE ID: $INSTANCE_ID"
+  pa_log "MTW_TRUST_POLICY: $MTW_TRUST_POLICY"
   INSTANCE_DIR=$INSTANCE_DIR/$INSTANCE_ID
   pa_log "INSTANCE_DIR: $INSTANCE_DIR"
-  pa_log "MTW_TRUST_POLICY: $MTW_TRUST_POLICY"
 
-  #if [ -n "$BASE_IMAGE" ]; then
   if [ -n "$TARGET" ]; then
      if [ -f $TARGET ]; then
          pa_log "Found base image: $TARGET"
@@ -217,9 +213,17 @@ pa_launch() {
         tar -xvf $TARGET -C $temp_dir
         ls -l $temp_dir >> $logfile
         mv $temp_dir/*.xml $trustPolicyTarget
-        #if [ -f $temp_dir/"*.img.*" ]; then
-           cp $temp_dir/"cirros"* $TARGET
-        ls -ltar $TARGET >> $logfile
+        pa_log "*******************************************"
+        image_path=`find $temp_dir -name '*.[img|vhd|raw]*'`
+        pa_log "Image Path is $image_path"
+        pa_log "*******************************************"
+        if [ -n $image_path ]; then
+           cp $image_path $TARGET
+        else
+            pa_log "Failed to untar and copy the image successfully"
+            exit 1
+        fi
+        #ls -ltar $TARGET >> $logfile
         echo $?
         pa_log "Untar the tar"
         #Untar
@@ -254,8 +258,8 @@ pa_launch() {
  
      #if the verification was successful, perform the xml parsing here
      cat $trustPolicyTarget | xmlstarlet fo --noindent | sed -e 's/ xmlns.*=".*"//g' | xmlstarlet sel -t -c "/TrustPolicy/Whitelist" | xmlstarlet ed -u '/Whitelist/*' -v '' | xmlstarlet ed -r "Whitelist" -v "Manifest" |xmlstarlet ed -r "/Manifest/@DigestAlg" -v 'xmlns="mtwilson:trustdirector:manifest:1.1" DigestAlg'> $INSTANCE_DIR/manifestlist.xml
-     cat $trustPolicyTarget >> $logfile
-     cat $INSTANCE_DIR/manifestlist.xml >> $logfile
+     #cat $trustPolicyTarget >> $logfile
+     #cat $INSTANCE_DIR/manifestlist.xml >> $logfile
      ls -l $INSTANCE_DIR >> $logfile
 
       #md5sum /var/lib/nova/instances/_base/$BASE_IMAGE >> $logfile
@@ -270,17 +274,16 @@ pa_launch() {
       local current_md5=$(md5 $TARGET)
       pa_log "Checksum after decryption: $current_md5"
       if [ "$current_md5" != "$CHECKSUM" ]; then
-        pa_log "Error: checksum is $current_md5 but expected $CHECKSUM"
+          pa_log "Error: checksum is $current_md5 but expected $CHECKSUM"
       fi
-    else
-       pa_log "The image is not encrypted"
+      else
+         pa_log "The image is not encrypted"
     fi
     else
-      #pa_log "File not found:  /var/lib/nova/instances/_base/$BASE_IMAGE"
-      pa_log "File not found: $TARGET"
+        pa_log "File not found: $TARGET"
     fi
-  else
-    pa_log "Missing parameter --target"
+   else
+       pa_log "Missing parameter --target"
   fi
   #if [ -d /var/lib/nova/instances/$INSTANCE_NAME ]; then
   #  INSTANCE_DIR=/var/lib/nova/instances/$INSTANCE_NAME 
@@ -378,7 +381,7 @@ pa_request_dek() {
   curl --insecure --silent -X POST -H "Content-Type: text/plain" --data-binary @$aikdir/aik.pem "$url" > $dekdir/mh.dek.base64
   #Uncomment the following line for new KMS integration and comment the above line
   #Uncomment the below line to integrate the KMS proxy
-  #curl --proxy http://$KMSPROXY_IPADDRESS:9080 --verbose -X POST -H "Content-Type: application/x-pem-file" -H "Accept: application/octet-stream" --data-binary @$aikdir/aik.pem  "$url" > $INSTANCE_DIR/$IMAGE_ID".key"
+  #curl --proxy http://$kms_proxy_ipaddress:9080 --verbose -X POST -H "Content-Type: application/x-pem-file" -H "Accept: application/octet-stream" --data-binary @$aikdir/aik.pem  "$url" > $INSTANCE_DIR/$IMAGE_ID".key"
 
   #export MH_DEK_RAW=`cat $dekdir/mh.dek`
   export MH_DEK_BASE64=`cat $dekdir/mh.dek.base64`
